name: Build docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * */7"
  push:
    branches:
      - master
    paths:
      - .github/workflows/image.yml  # This workflow file itself
      - .dockerignore
      - Dockerfile
      - build/docker-bake.hcl
      - rootfs/**
      - src/**
      - tests/**

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: tests/run-tests.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Get build date
        id: build-date
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/n0rthernl1ghts/docker-env-secrets
          cache-to: type=inline
          push: true
          pull: true
          tags: |
            ghcr.io/n0rthernl1ghts/docker-env-secrets:latest
            ghcr.io/n0rthernl1ghts/docker-env-secrets:git-${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.build-date.outputs.timestamp }}
